<a href="https://colab.research.google.com/github/kunal29july/Numpy/blob/main/NumPy_assign_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
# importing the NumPy library

import numpy as np

In [12]:
np_1 = np.arange(1,6)
np_1


array([1, 2, 3, 4, 5])

In [8]:
# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)
np_2

array([0., 0., 0., 0., 0.])

In [10]:
np_2=np.zeros(5,dtype="int")
np_2

array([0, 0, 0, 0, 0])

In [13]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[1 2 3 4 5]


In [14]:
# check the dimension of the arrays
# array np_1
np_1.ndim

1

In [15]:
# check the dimension of the arrays
np_2.ndim


1

In [16]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5)

# checking the created array:np_3
print(np_3)

[1. 1. 1. 1. 1.]


In [17]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


In [24]:
# creating an array of fixed length
np_4 = np.linspace(1,10,5)

# checking the created array:np_4
print(np_4)

[ 1.    3.25  5.5   7.75 10.  ]


In [25]:
# squaring the terms of np_1
np.power(np_1,2)

array([ 1,  4,  9, 16, 25])

In [26]:
# getting the absolute value of the elements
x=[-1,-2,-3]
np.absolute(x)

array([1, 2, 3])

In [27]:
# np.sin()
np.sin(x)


array([-0.84147098, -0.90929743, -0.14112001])

In [28]:
 np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [31]:
# np.log()
np.log(16)

2.772588722239781

### Empty arrays

In [ ]:
# Creating empty arrays

x = np.arange(1, 6)
y = 

# filling the empty array


In [ ]:
# printing the output obtained above
y

### Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition


In [ ]:
# Cummulative addition of elements at each element


In [ ]:
np.linalg

In [ ]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [32]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [33]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [34]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [35]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.36692459, 0.80499519, 0.70946741, 0.79192946],
       [0.80845815, 0.02918603, 0.69365777, 0.87662173],
       [0.90360787, 0.5039474 , 0.79724512, 0.10578572]])

In [37]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[2, 7, 6, 8],
       [0, 0, 8, 0],
       [1, 1, 7, 8],
       [8, 6, 5, 0]])